-- Script para crear la tabla ErrorLogs
-- Ejecutar en SQL Server

CREATE TABLE ErrorLogs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ErrorNumber NVARCHAR(50) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    StackTrace NVARCHAR(MAX) NULL,
    Source NVARCHAR(500) NULL,
    RequestPath NVARCHAR(500) NULL,
    RequestMethod NVARCHAR(10) NULL,
    UserAgent NVARCHAR(500) NULL,
    UserId NVARCHAR(100) NULL,
    RequestBody NVARCHAR(MAX) NULL,
    QueryString NVARCHAR(500) NULL,
    ExceptionType NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    Environment NVARCHAR(50) NULL,
    AdditionalData NVARCHAR(MAX) NULL
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IX_ErrorLogs_ErrorNumber ON ErrorLogs(ErrorNumber);
CREATE INDEX IX_ErrorLogs_CreatedAt ON ErrorLogs(CreatedAt);
CREATE INDEX IX_ErrorLogs_Environment ON ErrorLogs(Environment);
CREATE INDEX IX_ErrorLogs_UserId ON ErrorLogs(UserId);

-- Crear índice compuesto para búsquedas comunes
CREATE INDEX IX_ErrorLogs_Environment_CreatedAt ON ErrorLogs(Environment, CreatedAt);

-- Script para Oracle (si usas Oracle)
/*
CREATE TABLE ErrorLogs (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ErrorNumber VARCHAR2(50) NOT NULL,
    Message CLOB NOT NULL,
    StackTrace CLOB NULL,
    Source VARCHAR2(500) NULL,
    RequestPath VARCHAR2(500) NULL,
    RequestMethod VARCHAR2(10) NULL,
    UserAgent VARCHAR2(500) NULL,
    UserId VARCHAR2(100) NULL,
    RequestBody CLOB NULL,
    QueryString VARCHAR2(500) NULL,
    ExceptionType VARCHAR2(100) NULL,
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    Environment VARCHAR2(50) NULL,
    AdditionalData CLOB NULL
);

-- Crear índices para Oracle
CREATE INDEX IX_ErrorLogs_ErrorNumber ON ErrorLogs(ErrorNumber);
CREATE INDEX IX_ErrorLogs_CreatedAt ON ErrorLogs(CreatedAt);
CREATE INDEX IX_ErrorLogs_Environment ON ErrorLogs(Environment);
CREATE INDEX IX_ErrorLogs_UserId ON ErrorLogs(UserId);
CREATE INDEX IX_ErrorLogs_Environment_CreatedAt ON ErrorLogs(Environment, CreatedAt);
*/ 