<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ModelLayer\ModelLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BrandParthner\" />
    <Folder Include="Corporate\" />
    <Folder Include="Ecommerce\" />
    <Folder Include="Security\Commands\" />
    <Folder Include="Security\Validators\" />
    <Folder Include="Shared\Commands\" />
    <Folder Include="Shared\Queries\" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="EPPlus" Version="8.4.2" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.130" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
